# Generated by Django 5.2.8 on 2026-02-04 11:19

import apps.resources.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=100)),
                ('ano_letivo', models.CharField(max_length=2)),
                ('disciplina', models.CharField(max_length=100)),
                ('tipo_arquivo', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('PPTX', 'PPTX'), ('IMG', 'Imagem'), ('LINK', 'Link')], max_length=10)),
                ('instituicao', models.CharField(max_length=150)),
                ('professor', models.CharField(blank=True, max_length=150, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=apps.resources.models.resource_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'pptx', 'jpg', 'jpeg', 'png'])])),
                ('link', models.URLField(blank=True, null=True)),
                ('hash_arquivo', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('total_salvos', models.PositiveIntegerField(default=0)),
                ('total_reports_falsos', models.PositiveIntegerField(default=0)),
                ('data_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Aluno que enviou')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
