# Generated by Django 5.2.8 on 2026-02-04 12:21

import apps.resources.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=apps.resources.models.resource_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'pptx', 'ppt', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tipo_arquivo',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('PPTX', 'PPTX'), ('IMG', 'Imagem'), ('LINK', 'Link')], max_length=10),
        ),
    ]
