# Generated by Django 6.0.6 on 2026-06-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_add_phash'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='suspenso',
            field=models.BooleanField(default=False),
        ),
    ]
