# Generated by Django 5.2.8 on 2026-02-06 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_alter_resource_arquivo_alter_resource_tipo_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECURSO', 'Recurso'), ('USUARIO', 'Usuário')], default='RECURSO', max_length=10)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Resolvido (Recurso Removido)'), ('REJEITADO', 'Rejeitado (Falso Alerta)')], default='PENDENTE', max_length=10)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_feitos', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='resources.resource')),
                ('usuario_denunciado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
