# Generated by Django 5.2.8 on 2026-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Resolvido (Recurso Removido)'), ('REJEITADO', 'Rejeitado (Falso Alerta)')], default='PENDENTE', max_length=15),
        ),
    ]
