# Generated by Django 5.2.8 on 2026-02-05 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_alter_resource_arquivo_alter_resource_tipo_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Escreva a sua dúvida, agradecimento ou sugestão.', verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar este comentário (ex: conteúdo impróprio) sem o apagar.', verbose_name='Visível no site?')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='resources.resource', verbose_name='Recurso comentado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
