# Generated by Django 6.0.6 on 2026-07-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_atualizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar este comentário sem o apagar.', verbose_name='Visível no site?'),
        ),
    ]
