# Generated by Django 5.2.8 on 2026-03-23 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDO', 'Resolvido'), ('REJEITADO', 'Rejeitado (Falso Alerta)')], default='PENDENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='tipo',
            field=models.CharField(choices=[('RECURSO', 'Recurso'), ('USUARIO', 'Utilizador')], default='RECURSO', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='usuario_denunciado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_recebidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
