# Generated by Django 6.0.6 on 2026-06-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_motivo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tipo',
            field=models.CharField(choices=[('RECURSO', 'Recurso'), ('USUARIO', 'Utilizador'), ('IA', 'Moderação automática')], default='RECURSO', max_length=10),
        ),
    ]
