# Generated by Django 5.2.8 on 2026-03-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_arquivo_alter_resource_tipo_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='total_reports_falsos',
        ),
    ]
