# Generated by Django 6.0.6 on 2026-06-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_resource_curso_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='phash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='resource',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Título do recurso'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tipo_arquivo',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('PPTX', 'PPTX'), ('IMG', 'Imagem')], max_length=10),
        ),
    ]
