# Generated by Django 6.0.6 on 2026-06-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_add_suspenso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='hash_arquivo',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
